name: failing-ci

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  failing-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run app
        run: |
           python app.py

# Failure 1: The app.py file is missing, which will cause the "Run app" step to fail.      
      # - name: Run tests
      #   run: |
      #     echo "Running tests..."
      #     python tests/test_app.py

# Failure 2: The Dockerfile references a non-existent base image "test:1.2.3", which will cause the "Docker build" step to fail.
      - name: Docker build
        run: |
          echo "Building Docker image..."
          docker build -t cicd-demo:latest .
